### ISSUE TITLE
how do i add enemies?

### ISSUE THREAD

**Issue by asdwastakenig** [ImNotSimon/Vanity-tool#1]
its missing in the spite prefab thing

**Comment by ImNotSimon** [comment]
enemies are found inside the ULTRAKILL Assets/Exported Project/Assets/PrefabInstance folder.

for more info:
wiki: https://layzyidiot.github.io/e-sw/
discord: https://discord.gg/RY8J67neJ9

**Comment by asdwastakenig** [comment]
whoops, sorry yeah was kinda intoxicated while writing sorry! plz Close it
off i forgot my password

ImNotSimon ***@***.***> schrieb am So., 2. Juni 2024, 00:50:
